#!/bin/sh

# Exit on error
set -e

case "$1" in
    configure)
        if [ ! -f @pkg_path@/poe-gen-tool ]; then
            echo "ERROR: @pkg_path@/poe-gen-tool not found." >&2
            exit 1
        fi

        ln -s -f @pkg_path@/poe-gen-tool /usr/local/bin/poe-gen-tool
        ;;
esac
